nuxt-content/mdc

- playground/app.vue
- src/runtime/parser/handlers/code.ts
- src/runtime/parser/handlers/utils.ts
- src/runtime/parser/shiki.ts
- src/runtime/shiki/event-handler.ts
- src/runtime/shiki/highlighter.ts
- src/runtime/shiki/types.ts
Supposed to fix #19 when ready
Currently, investigating where the highlights go missing in the process...
If you have any ideas, please share them.
---
In this function we never add/use highlights:
https://github.com/nuxt-modules/mdc/blob/9c357bf0fa12c2bf289ce432f8d4970b9738910c/src/runtime/parser/shiki.ts#L17
https://github.com/nuxt-modules/mdc/blob/9c357bf0fa12c2bf289ce432f8d4970b9738910c/src/runtime/parser/shiki.ts#L39
> fix: pass missing highlight class

- .github/scripts/bump-edge.ts
- .github/scripts/utils.ts
- README.md
- playground/app.vue
- src/runtime/components/MDCRenderer.vue
- src/runtime/parser/compiler.ts
- src/runtime/parser/handlers/inlineCode.ts
- src/runtime/parser/index.ts
- src/runtime/parser/shiki.ts
- src/runtime/utils/node.ts
- src/runtime/utils/ssrSlot.ts
- test/markdown/empty-paragraph.test.ts
- test/markdown/excerpt.test.ts
- test/markdown/heading-id.test.ts
- test/markdown/inline-code-highlighted.test.ts
- test/markdown/inline-code-props.test.ts
- test/markdown/inline-code.test.ts
- test/markdown/unwrap-slot.test.ts
- test/markdown/xss.test.ts
fixes nuxt/content#2316
Also parse `code` tag if it has a `language` prop.
> **Important**
> We probably have to add back `lang` instead of supporting *only* `language`, right? 
> Otherwise, this breaking change has to be mentioned (and changed everywhere in the docs, etc.).
What do you think about that?
Edit: added back support for `lang` property.
---
Also, for me, a general PR template would be helpful :)
> fix: inline code highlighting

- playground/app.vue
- src/runtime/components/prose/ProsePre.vue
- src/runtime/shiki/highlighter.ts
- test/markdown/code-block-highlighted.test.ts
- test/markdown/inline-code-highlighted.test.ts
resolve nuxt/content#2366
Will try to drop `!important` rules, to allow overriding them without the need to specify `!important` yourself.
- use no default for code block color scheme, to allow overriding without `!important`
- update tests
---
On the side also changed:
- use `\200b` instead of `1rem` (which is not (necessarily) the right height) to keep line height of empty lines;
`\200b` is a no-width line height blank character
- fixed highlight color display for project dev mode
The `!important` [here](https://github.com/nuxt-modules/mdc/pull/61/files#diff-4e70dbb4315c851802969484f0b6cf566eda24aeb43dc8b6c413e575488713d0R62) is just for dev purposes in this project, and is applied, because the current specificity is not high enough to override the other rule (could also change that …
> fix: drop !important css rules from code highlighting

- src/runtime/shiki/highlighter.ts
- test/markdown/code-block-highlighted.test.ts
- test/markdown/inline-code-highlighted.test.ts
At the moment, the style generated looks like this:
Removing the `html` selector would let us highlight with the dark theme when in light mode by adding the `dark` class on a section.
Example of what we're trying to do on nuxt.com (we can see its using the light theme although I've added a `dark` class around):
> feat(shiki): remove `html` from `.shiki` css selector

- src/runtime/types/tree.ts
Hello,
Even if there is no filename, heading 1 or title in frontmatter, the data object always have a title key and a description key.
Adding these will allow use to remove `| undefined` in https://github.com/nuxt/content/blob/5f059f81478ef6e64c5a63db9da24b80ae337176/src/runtime/types/index.d.ts#L20
> feat: add title and description on markdown returned type

- src/runtime/components/MDC.vue
Change import { ... } from '../types' to import type { ... } from '…/types' to support TypeScript ^3.8
> Change import to import type

- src/runtime/components/MDCRenderer.vue
- src/runtime/components/prose/ProseScript.vue
Sometimes when building a blog with markdown, using Gist is essential, but mdc did not have support for rendering script tag, this was my problem when I tried to use Gist on my Blog.
Each and every script was rendered as simple text like the following: `<script>`.
I added a `ProseScript` which by default also doesn't render the script, just a warning message, but now the user can override this element with their own, just like the other `Prose*` elements.
My issue is: #70
> feat: add script render in mdc

- src/runtime/components/MDCRenderer.vue
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
> fix: import nuxt composables from #imports

- .github/workflows/ci.yml
This fixes the release job conditional so it only checks the merge commit title and not the squashed commits in the commit body. This could incorrectly skip/prevent a release if the body contains one of the checked keywords.
> ci: fix release job conditional

- src/runtime/shiki/highlighter.ts
- src/runtime/shiki/index.ts
fixes #72
- pass code to highlighter too, if `highlights` are defined
- check if `lang` cannot be loaded by `shikiji`:
- highlights defined? Set `lang` to `''`
- otherwise, pass on `lang not found` error
- text/without `lang` has `<span><span>text</span</span>` as children (highlighted empty line has no children)
It might be better to change the last point in `shiki` / `shikiji`? (And then remove line `86`-`88` here)
---
> [!Note]
> I'm not sure, if it is better when all code block code's (regardless of highlighting (code / lines) or not) should be split to lines.
> Then every code block would behave the same when they are styled.
> This would work by just not differentiating if it has line highlights or not when changing the language to `''` and also changing the `if` statement for …
> feat(highlighter): support text/unknown/no language line highlights

- src/module.ts
https://github.com/nuxt/nuxt/issues/24196#issuecomment-1853505843
While https://github.com/vitejs/vite/pull/15337 fixes it on the upstream, I still think it's better for us to also do the check so it works for existing users
> fix: only append new entry to `optimizeDeps` on `vite:extendConfig`

- .gitignore
- package.json
- pnpm-lock.yaml
- src/module.ts
- src/runtime/shiki/event-handler.ts
Currently, the MDC module enables an experimental feature of nitro for wasm which will change its behavior in the next minor release.
This PR directly adds [unjs/unwasm](https://github.com/unjs/unwasm) plugin + additional patches to replicate the latest implementation of nitro.
Notes:
- This patch is essential to be released before Nitro Minor to avoid breaking current users
- I don't expect significant API changes for unwasm binding and nitro but there is still a chance and until then we need to keep it in sync so please have an eye on upstream @farnabaz 
- Users implicitly getting opted-in to wasm experiment, should be fine with this but if they somehow manually enable `experimental.wasm`, they need to make sure to use latest nitro/nightly
> feat: enable wasm with unwasm for highlighter

- src/module.ts
resolves #121
Currently, few packages are specified in the optimize list: https://github.com/nuxt-modules/mdc/blob/main/src/module.ts#L56
Most of them work only based on implicit hoisted dependencies that install them. Now `is-buffer` is not used or installed by any sub-dependency and causes this issue. It should be removed.
For others `['debug', 'flat', 'node-emoji', 'extend', 'hast-util-raw']` most of them are fragile. `flat` is for example only used by c12 and another random package. As a later solution if you don't prefer to explicitly list them, we might try to resolve them and remove if failed. (could be also a protection logic in nuxt core https://github.com/nuxt/nuxt/issues/24927 /cc @danielroe wdyt?)
Also as a best practice, I highly recommend (I beg you!) please specify any kind …
> fix: remove `is-buffer` from optimize deps

- src/module.ts
- src/types.ts
Include `md`, `mdc`, `yaml`, `tsx`, `jsx` into the default langs to make it easier to use. For ppl who care about the bundle size and not using all the langs, they can always override this array to provide custom list.
> feat: add more default highlight langs

- src/templates/mdc-imports.ts
fixes nuxt/content#2542
[Scule](https://github.com/unjs/scule) seems to not strip non-word-chars on conversion (except for [probably `['-', '_', '/', '.']`](https://github.com/unjs/scule?tab=readme-ov-file#splitbycasestr-splitters)).
So the `@` character is left as the start of an import name.
Should this maybe be changed in Scule too?
The replacement could also be done before passing the string to Scule, if preferred.
I haven't tested this properly, but as far as I can see, this should be the proper fix.
> fix: strip non-word-chars from library import name

- package.json
this PR add types to the exports object for the package.json to avoid issue when this used.
fix #88
> build: exports types

- README.md
- src/module.ts
- src/runtime/components/MDCRenderer.vue
- src/runtime/components/prose/ProseScript.vue
- src/runtime/highlighter/rehype-nuxt.ts
- src/runtime/highlighter/rehype.ts
- src/runtime/highlighter/shiki.ts
- src/runtime/index.ts
- src/runtime/parser/index.ts
- src/runtime/types/parser.ts
- test/utils/parser.ts
Allow utilizing the `MDCRenderer.vue` component and `parseMarkdown` utility in a normal Vue app, outside Nuxt. 
I've updated the `@nuxtjs/mdc` module in this PR along with updates to the primary README for usage instructions.
I've also created a [CodeSandbox demo](https://codesandbox.io/p/devbox/mdc-in-vue-vd7thh) by building the package, running `npm pack`, and importing the changes into the sandbox via a local `nuxtjs-mdc-local.tgz` bundle.
Please see the README file in the PR as well as the CodeSandbox for a usage example.
@farnabaz @antfu I'd appreciate some eyes on this; mainly around:
1. Is defining import aliases in the host project's Vite config the best way to get around the Nuxt-specific imports that aren't needed? I don't like the host app having to include the aliases and the …
> feat: use mdcrenderer component and parsemarkdown util outside nuxt

- src/module.ts
resolves https://github.com/nuxt/content/issues/2381
Vite requires dependencies that are optimised to be installed, but none of these deps will be directly installed by users (or they have to add them, which is a negative user experience). So we can indicate to vite to resolve the dependency from within another dependency that _is_ installed, in this case `@nuxtjs/mdc`...
If the user does _not_ have `@nuxtjs/mdc` (e.g. because nuxt/content is installing it) then we will have to modify these dependencies upstream.... (see linked PR in nuxt/content)
> fix: optimise deps with nested config

- README.md
Given the provided example, we need to import the default export, not a named export.
> docs: use default export

- README.md
- docs/content/0.index.md
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
> docs: use new `nuxi module add` command in installation

- src/module.ts
A type issue in the newly released version 0.7.0 and introduced by #180 seems to be that the runtime config type wasn't updated to include the `useNuxtImage` type which is causing `nuxi typecheck` to fail with the error:
```bash
node_modules/.pnpm/@nuxtjs+mdc@0.7.0_rollup@4.17.2/node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue:15:52 - error TS2339: Property 'useNuxtImage' does not exist on type '{ components: { prose: boolean; map: Record<string, string>; }; headings: { anchorLinks?: { h1?: boolean | undefined; h2?: boolean | undefined; h3?: boolean | undefined; h4?: boolean | undefined; h5?: boolean | undefined; h6?: boolean | undefined; } | undefined; } | undefined; }'.
15 const imgComponent = useRuntimeConfig().public.mdc.useNuxtImage ? resolveComponent('NuxtImg') : …
```
> fix(types): Add `useNuxtImage` type into runtime config

- src/module.ts
- src/types.ts
There is a double entry for "vue"in supported highlight languages.
This PR fixes this.
> fix double entry for "vue" highlight language

- src/types.ts
Adding `false` as accepted value for `headings.anchorLinks` option, as discussed here: #203
> fix: add `false` as accepted value for `headings.anchorLinks` option

- src/module.ts
Add the `cloudflare-module` [Nitro preset](https://nitro.unjs.io/deploy/providers/cloudflare#cloudflare-module-workers) to the list of presets to check for to determine whether `useWasmAssets` should return `true`.
> fix(wasm): include cloudflare-module preset

- package.json
- src/module.ts
- src/runtime/components/prose/ProseH1.vue
- src/runtime/components/prose/ProseH2.vue
- src/runtime/components/prose/ProseH3.vue
- src/runtime/components/prose/ProseH4.vue
- src/runtime/components/prose/ProseH5.vue
- src/runtime/components/prose/ProseH6.vue
Fix build by referencing `runtime/*.js` files rather than `*.mjs`.
`@nuxt/module-builder` [introduced a breaking change in 0.7.0](https://github.com/nuxt/module-builder/releases/tag/v0.7.0) to use `.js` extension for files in the `runtime/` directory
The `ProseH*.vue` components still had a type checking error. This PR resolves the types.
> fix(build): resolve runtime/**/*.js files and prose header types

- src/config.ts
- src/module.ts
In the latest version, importing `@nuxtjs/mdc/config` (used in runtime, mdc.config.js) would imports the whole `@nuxtjs/mdc`, which is node side. This is because the `dist/config.mjs` get bundled as:
```ts
export { defineConfig } from './module.mjs'; // <-- this introduce side-effects
import 'node:fs';
import '@nuxt/kit';
import 'defu';
import 'pathe';
import 'node:fs/promises';
import 'scule';
```
Which was introduced in https://github.com/nuxt-modules/mdc/issues/226
This would cost `nuxt-content-twoslash` gets error like this: (would appear in every usage in `mdc.config.js`
> fix: `defineConfig` should be side-effect free

- package.json
- pnpm-lock.yaml
- src/runtime/highlighter/shiki.ts
See https://github.com/shikijs/shiki/pull/702
`getHighlighterCore` is renamed to `createHighlighterCore`
> feat: upgrade shiki, support custom embedded languages `ts-type` and `vue-html`

- src/runtime/components/MDC.vue
- src/runtime/components/prose/ProseA.vue
- src/runtime/components/prose/ProseH1.vue
- src/runtime/components/prose/ProseH2.vue
- src/runtime/components/prose/ProseH3.vue
- src/runtime/components/prose/ProseH4.vue
- src/runtime/components/prose/ProseH5.vue
- src/runtime/components/prose/ProseH6.vue
- src/runtime/components/prose/ProseImg.vue
In vue 3.5 and latest Nuxt version, typing errors are thrown when accessing `props` directly. These errors look like:
```sh
node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue:2:12 - error TS2339: Property 'id' does not exist on type 'CreateComponentPublicInstanceWithMixins<Readonly<{}> & Readonly<{}>, { generate: typeof generate; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 17 more ..., {}>'.
2   <h6 :id="id">
~~
node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue:4:13 - error TS2339: Property 'id' does not exist on type 'CreateComponentPublicInstanceWithMixins<Readonly<{}> & Readonly<{}>, { generate: typeof generate; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 17 more ..., {}>'.
4       v-if="id && generate"
```
This …
> fix: Use explicit `props`

- package.json
- playground/nuxt.config.ts
- pnpm-lock.yaml
- src/module.ts
- src/runtime/highlighter/shiki.ts
- src/templates/mdc-highlighter.ts
- src/types/module.ts
- test/utils/parser.ts
This allows the MDC module and Nuxt Content to utilize the new JavaScript engine of Shiki (https://shiki.style/guide/regex-engines), which produces smaller and more portable bundles. Currently, it requires explicit opt-in as the engine is still experimental.
> feat: introduce `highlight.shikiEngine` option

- src/module.ts
- src/runtime/components/prose/ProseImg.vue
Feature added in https://github.com/nuxt-modules/mdc/pull/180 to use `<NuxtImg>` under the hood, but now that this is stubbed in Nuxt, this will always result in a transform (and potentially a prompt to install `@nuxt/image` - see https://github.com/nuxt/nuxt/issues/29283).
In future releases of Nuxt this will cause a hard error (https://github.com/nuxt/nuxt/pull/29287), so this PR refactors things to only import from NuxtImg when it doesn't point to a stubbed version.
> fix: do not load `<NuxtImg>` stub if it is not installed

- src/module.ts
- src/runtime/parser/options.ts
- src/templates/mdc-imports.ts
- src/types/module.ts
- test/utils/parser.ts
resolves https://github.com/nuxt-modules/mdc/issues/187
Move remark/rehype default plugin to module options so they can disable easily and remove from production bundle.
> fix(module): possibility to remove module's default remark/rehype plugins from bundle

- playground/components/global/PageSnippet.vue
N/a
Since the playground is used as an example reference on GitHub, update the syntax to resolve proper syntax highlighting in the browser.
> chore(playground): update syntax for github highlighting

- src/module.ts
Resolves #285 (this util is what I was going for with `parseAst`)
As I was going to test the new `stringifyMarkdown` util I've noticed it was not added to Nuxt and Nitro imports.
> fix: `stringifyMarkdown` auto-import

- src/runtime/stringify/index.ts
Based on https://github.com/syntax-tree/mdast-util-to-markdown/issues/65#issuecomment-2470466050 it is necessary to use `*` instead of `_` fo emphasis. We should use it and suggest users to use it.
> fix(stringify)!: use `*` instead `_` for emphsis syntax

- src/runtime/parser/utils/props.ts
- test/markdown/images.test.ts
Issue #338 
The following fixes a regression in prior commit which fixed an XSS vulnerability but didn't account for relative or absolute paths.
This code also introduces a sanity test that will catch this in the future.
> fix: regression in allowed image links using absolute or relative paths

- src/runtime/parser/utils/props.ts
- test/markdown/images.test.ts
- test/markdown/xss.test.ts
Follow-up from fixes to support static file paths like `src/assets` where there is no leading directory character
> fix: support static file paths

- README.md
resolves #346 and #175 and possibly #342
The docs don't tell you that custom prose components need to be globally registered for MDC to pick up on them. Multiple users seem to have been confused by this. It's possible that globally registering the prose components is not the preferred solution but to the best of my knowledge this is how to do it.
> docs: Clarifies the need to globally register the custom prose components

- src/runtime/components/MDC.vue
- src/runtime/parser/index.ts
- src/types/parser.ts
This PR changes the default behavior of MDC component. MDC component will treat markdown contents as partial contents, meaning that auto-generated  fields (title, description and toc) will not generate.
> !fix(MDC): do not generate title/description and toc

- src/utils/vue-mdc-slot.ts
No issue yet
This PR adds support for the camelCase variant of `mdc-unwrap` to be detected as well. This casing is what Vue officially recommends for props ([see the docs](https://vuejs.org/guide/components/props.html#prop-name-casing)).
We noticed unwrap didn't work for us as the official `vue/prop-name-casing` ESLint rule autofixes props to `camelCase` for us. ([see the docs](https://eslint.vuejs.org/rules/prop-name-casing.html))
> fix: detect mdcUnwrap on slots too
